config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to: 'dashboards#show'
  get '/my_trips', to: 'dashboards#my_trips'
  get '/my_flats', to: 'dashboards#my_flats'
  patch '/bookings/:id/approve', to: 'bookings#change_status_approve', as: 'booking_approve'
  patch '/bookings/:id/decline', to: 'bookings#change_status_decline', as: 'booking_decline'

  resources :flats do
    resources :bookings  do
      resources :reviews, only: [:new, :create]
    end
  end

  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  has_many :reviews
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true

  def approved
    self.booking = "Aproved"
  end

end

app/models/flat.rb
class Flat < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  geocoded_by :address
  validates :photo, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def host?
    self.flats.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @flat = Flat.find(params[:flat_id])
    @bookings = Booking.where(flat_id: params[:flat_id])
  end

  def show
    @flat = Flat.find(params[:flat_id])
    # REVIEW FORM
    @review = Review.new
    # CRYPTO PAYMENT
    @address = "1Chain4asCYNnLVbvG6pgCLGBrtzh4Lx4b"
    url = "https://api-r.bitcoinchain.com/v1/address/utxo/#{@address}"
    # response = RestClient.get(url)
    # @data = JSON.parse(response)
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
    @price = 0
  end

  def create

    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)

    @booking.total_price = (@booking.end_date - @booking.start_date).to_i * @flat.price #saving price
    @booking.flat = @flat
    @booking.user = current_user

    if @booking.save
      redirect_to flat_booking_path(@flat, @booking)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:flat_id])
  end

  def update
    @flat = Flat.find(params[:flat_id])
    @booking.update(booking_params)
    @booking.total_price = (@booking.end_date - @booking.start_date).to_i * @flat.price #saving price
    @booking.save
    redirect_to flat_booking_path(@flat, @booking)
  end

  def destroy
    @flat = Flat.find(params[:flat_id])
    @booking.destroy
    redirect_to flat_path(@flat)
  end

  # def change_status
  #   @flat = Flat.find(params[:flat_id])
  #   @booking = @flat.booking


  #   # _approve

  #   # @booking.status = "Approved"
  #   # @booking.save
  #   # redirect_to my_flats_path
  # end
  def change_status_approve
    @booking = Booking.find(params[:id])
    @booking.status = "Approved"
    @booking.save
    redirect_to my_flats_path
  end

  def change_status_decline
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save
    redirect_to my_flats_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController


  def my_trips
    @trips = current_user.bookings
  end

  def my_flats
    @host = current_user.host?
    if @host
      @my_flats = current_user.flats
      @my_bookings = Booking.where(flat_id: @my_flats.pluck(:id))
    end
  end

  def show
    @host = current_user.host?
    @trips = current_user.bookings
    if @host
      @my_flats = current_user.flats
      @my_bookings = Booking.where(flat_id: @my_flats.pluck(:id))
    end
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    # @flats = Flat.all

     if params[:query].present?
      @flats = Flat.search_by_name_and_address(params[:query])
    else
      @flats = Flat.all
    end
    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
      }
    end
  end

  def show
        @markers =
      [{
        lat: @flat.latitude,
        lng: @flat.longitude,
      }]
      @address = "1Chain4asCYNnLVbvG6pgCLGBrtzh4Lx4b"
    url = "https://api-r.bitcoinchain.com/v1/address/utxo/#{@address}"
    # response = RestClient.get(url)
    # @data = JSON.parse(response)
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end


  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
    @flats = Flat.all
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def new
  #   @booking = Booking.find(params[:booking_id])
  #   @review = Review.new
  # end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to flat_booking_path(@flat, @booking)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [flat, booking] do |f| %>
  <%= f.input :start_date, as: :string, required: true, input_html: { class: 'datepicker' }  %>
  <%= f.input :end_date, as: :string, required: true, input_html: { class: 'datepicker' }   %>

  <%= f.submit button_text, class: "btn btn-green" %>
<% end %>

app/views/bookings/change_status.html.erb
<h1>Bookings#change_status</h1>
<p>Find me in app/views/bookings/change_status.html.erb</p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<div class="banner booking-banner" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.6) 0%, rgba(240,240,240,0.6) 50%), url('<%= cl_image_path @flat.photo %>');">
<div class="booking-container">
  <h2 id="reservation">Edit reservation for:</h2>
  <div class="row">
    <div class="col-sm-6">
      <h1><strong><%= @flat.name %></strong></h1>
      <h4><strong>Host Name:</strong> <%= @flat.user.name %></h4>
      <p><strong>Description:</strong> <%= @flat.description %></p>
    </div>
    <br>
    <div class="col-sm-6">
      <%= render 'form', booking: @booking, flat: @flat, button_text: "Edit Booking"%>
      <h3>TOTAL_PRICE: </h3>
    </div>
  </div>
</div>
</div>

app/views/bookings/index.html.erb
<h1>Bookings for:</h1>

<h1><%= @flat.id %></h1>
<h1><%= @flat.name %></h1>



<% @bookings.each do |booking| %>
  <ul>
    <li>
      <p>Booking Id: <%= booking.id %></p>


    </li>
  </ul>
  <% end %>

app/views/bookings/new.html.erb
<div class="banner booking-banner" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.6) 0%, rgba(240,240,240,0.6) 50%), url('<%= cl_image_path @flat.photo %>');">
<div class="booking-container">
  <h2 id="reservation">New Reservation for:</h2>
  <div class="row">
    <div class="col-sm-6">
      <h1><%= @flat.name %></h1>
      <h6><strong>Description:</strong> <%= @flat.description %></h6>
      <p><strong>Host:</strong> <%= @flat.user.name %></p>
      <h2>$</h2><h2 id="price"><%=@flat.price %><h2>per Night</h2>
    </div>
    <h1></h1>
    <div class="col-sm-6">
      <%= render 'form', booking: @booking, flat: @flat, button_text: "Send booking request", class: "btn btn-xs btn-green" %>
      <h4>TOTAL_PRICE: $</h4><h4 id="total-price"></h4>
    </div>
  </div>
</div>
</div>

app/views/bookings/show.html.erb
<div class="banner booking-banner" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.6) 0%, rgba(240,240,240,0.6) 50%), url('<%= cl_image_path @flat.photo %>');">

  <div class="booking-container">
    <h2 id="reservation">Booking request sent for:</h2>
    <div class="row">
      <div class="col-sm-6">
        <h1><strong><%= @flat.name %></strong></h1>
        <h4><strong>Host:</strong> <%= @flat.user.name %></h4>
        <h6><strong>Description:</strong> <%= @flat.description %></h6>
      </div>

      <div class="col-sm-6">
        <h1></h1>
        <p><strong>Check-in:</strong> <%= @booking.start_date %></p>
        <p><strong>Check-out:</strong> <%= @booking.end_date %></p>
        <p><strong>Days of Reservation:</strong> <%= (@booking.end_date - @booking.start_date).to_i %></p>
        <p><strong>Total Price:</strong> $<%= @booking.total_price %></p>
        <p><strong>Reservation Status:</strong> <%= @booking.status %></p>
        <br>
        <%= link_to "Change Dates", edit_flat_booking_path(@flat, @booking), class: "btn btn-xs btn-green" %>
        <%= link_to "Cancel Booking", flat_booking_path(@booking.flat, @booking), class: "btn btn-xs btn-green", method: :delete, data: {confirm: "Are you sure?"} %>

        <% if @booking.reviews.empty? %>
        <button type="button" class="btn btn-xs btn-green" data-toggle="modal" data-target="#exampleModal">
          Add a Review
        </button>
        <% end %>

      </div>
    </div>
  </div>
</div>

<% if !@booking.reviews.empty? %>
          <div class="booking-container">
            <h2 id="reservation">Review Flat and Booking:</h2>
            <div class="row">
              <div class="col-sm-6 col-offset-3">
                <% @booking.reviews.each do |review| %>
                <%= review.content %>
                <h4><strong>Client Name:</strong><%= review.booking.user.name %></h4>
                <% end %>
                <h5><strong>Host name:</strong> <%= @flat.user.name %></h5>
              </div>
            </div>
          </div>

<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Add a Review</h2>
        <h5><strong>Host name:</strong> <%= @flat.user.name %></h5>
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
      </div>
      <div class="modal-body">
        <% if @booking.reviews.empty? %>

        <%= simple_form_for [@flat, @booking, @review] do |f| %>
        <%= f.input :content %>
        <%= f.submit class: "btn btn-xs btn-green" %>
        <% end %>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/dashboards/_my_bookings.html.erb
    <div class="container-dashboard">
      <% @my_flats.each do |flat| %>
      <div class="flexed-items">
          <%= link_to flat_path(flat) do %>
        <div class="half-items flat">
          <div class="flat-card" style="background-image: linear-gradient(-225deg, rgba(200,200,200,0.15) 0%, rgba(150,150,150,0.6) 50%), url('<%= cl_image_path flat.photo%>');">
            <div class="flat-name">
              <h2><%= flat.name %></h2>
            </div>
            <div class="flat-location">
              <h4><%= flat.address %></h4>
            </div>
          </div>
            <% end %>
        </div>


        <div class="half-items booking">
          <h6>Bookings for this flat: <%= flat.bookings.count %> </h6>
          <hr>

          <div class="scroll-box">
            <% flat.bookings.each do |booking|%>
            <div class="booking" id="bookingcard">
              <img class="image-bordered" src="https://source.unsplash.com/200x200/?treehouse">
              <div class="booking-guest text-right">
                <p>Guest:</p>
                <hr>
                <p><%= booking.user.email %></p>
              </div>
              <div class="booking-body text-center">
                <h4><%= booking.flat.name %></h4>
                <p><%= booking.start_date %> - <%= booking.start_date %></p>
              </div>
              <div class="booking-status">
                <p>Status:</p><p class="status pending"> <%= booking.status %></p>

                <% if booking.status == "Pending" %>

                <%= link_to "Approve", booking_approve_path(booking), method: :patch, class: "btn btn-status btn-success" %>
                <%= link_to "Decline", booking_decline_path(booking), method: :patch, class: "btn btn-status btn-danger" %>

                <% end %>
                <p class="price">Total price: <%= booking.total_price %></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/dashboards/_my_houses.html.erb
<div class="house-container">
  <div class="row">

    <% @my_flats.each do |flat| %>

    <div class="col-md-12">
        <%= link_to flat_path(flat) do %>
        <% if flat.photo.file == nil %>
          <div class="house-card" style="background-image: linear-gradient(rgba(255,255,255,0.15), rgba(220,220,220,0.3)), url('<%= asset_path("jungle_leaves.jpeg") %>')">
            <%  else %>
          <div class="house-card" style="background-image: linear-gradient(rgba(255,255,255,0.15), rgba(255,255,255,0.5)), url('<%= cl_image_path flat.photo %>')">
        <% end %>
            <div class="card-category">
              <h3><%= flat.name %></h3>
            </div>
            <div class="card-description">
              <h2>$<%= flat.price %></h2>
              <p><%= flat.address %></p>
            </div>
          </div>
    <% end %>
    </div>

    <% end %>



  </div>
</div>

app/views/dashboards/_my_trips.html.erb
<style>
  #trips a {
    text-decoration: none !important;
    color: black;
  }
</style>

<div id="trips">
  <% @trips.each do |trip|%>
    <%= link_to flat_booking_path(trip.flat_id, trip) do %>
      <div class="trip">
        <img class="image-square" src="<%= cl_image_path trip.flat.photo%>">
        <div class="trip-body">
          <h3><%= trip.flat.name %>, <%= trip.flat.address %></h3>
          <h4><%= trip.start_date %> - <%= trip.start_date %></h4>
        </div>
        <div class="trip-name">
          <h6> <%= trip.flat.user.name %></h6>
        </div>
        <div class="trip-status">
          <p class="trip-price">Total price: <%= trip.total_price %></p>
          <p class="status pending">Status: <%= trip.status %></p>
        </div>
      </div>
    <% end %>
  <hr>
  <% end %>
</div>

app/views/dashboards/my_trips.html.erb
<h1>My Upcoming Trips</h1>


<% @trips.each do |trip|%>
<div class="trip">

  <img class="image-square" src="<%= cl_image_path trip.flat.photo%>">
    <div class="trip-price">
    <p>Host: <%= trip.flat.user.email %></p>
    </div>
  <div class="trip-body">
    <h3><%= trip.flat.name %></h3>
    <h4><%= trip.flat.address %></h4>
    <p><%= trip.start_date %> - <%= trip.start_date %></p>
  </div>
  <div class="trip-status">
    <p class="status pending">Status: <%= trip.status %></p>
    <p class="trip-price">Total price: <%= trip.total_price %></p>
  </div>
</div>
<% end %>

app/views/dashboards/show.html.erb
 <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#trips" aria-controls="trips" role="tab" data-toggle="tab">My Upcoming Trips</a>
    </li>
    <% if @host %>
    <li role="presentation"><a href="#my-bookings" aria-controls="my-bookings" role="tab" data-toggle="tab">My Bookings </a></li>
    <% end %>
    <% if @host %>
    <li role="presentation"><a href="#my-houses" aria-controls="my-houses" role="tab" data-toggle="tab">My Houses </a></li>
    <% end %>
</ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="trips">
      <%= render 'my_trips' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="my-bookings">
      <% if @host %>
      <%= render 'my_bookings' %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="my-houses">
     <% if @host %>
      <%= render 'my_houses' %>
      <% end %>
    </div>
  </div>


<% content_for :after_js do %>
  <script type="text/javascript">
    $('#myTabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
  </script>
<% end %>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
<%= f.input :name, placeholder: "Please enter a name" %>
<%= f.input :address, placeholder: "Please enter an address" %>
<%= f.input :description, placeholder: "Please add a description" %>
<%= f.input :price, placeholder: "Please enter a price per night" %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit "Save", class: "btn btn-xs btn-green"  %>
<%= link_to 'Back', flats_path, class: "btn btn-xs btn-green"  %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
 <h1 class="text-center">Edit details</h1>
 <div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/flats/index.html.erb
<div class="content">
  <div class="cards-container">
    <div class="row">
      <% @flats.each do |flat| %>
      <div class= "col-xs-12 col-sm-4">
        <%= link_to flat_path(flat) do %>
      <% if flat.photo.file == nil %>
      <div class="card" style="background-image: linear-gradient(rgba(10, 41, 11, 0.32), rgba(5, 23, 6, 0.32)), url('<%= asset_path("jungle_leaves.jpeg") %>')">
        <%  else %>
        <div class="card" style="background-image: linear-gradient(rgba(10, 41, 11, 0.32), rgba(5, 23, 6, 0.32)), url('<%= cl_image_path flat.photo %>')">
          <% end %>
          <div class="card-category">
            <h3><%= flat.name %></h3>
          </div>
          <div class="card-description">
            <h2>$<%=flat.price %> per night</h2>
            <p><%= flat.address %></p>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
     </div>
   </div>
   <br>
   <div id="map" data-markers="<%= @markers.to_json %>"></div>
 </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class="text-center">Add a new hut</h1>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form', flat: @flat, button_text: "Create New Hut" %>
    </div>
  </div>
</div>
<br>

app/views/flats/show.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://a0.muscache.com/im/pictures/15273358/d7329e9a_original.jpg?aki_policy=xx_large');">
</div>
-->

<div id="myImg" alt="<%= @flat.name %>" src="<%= cl_image_path @flat.photo %>" class="banner flat-banner" style="background-image: linear-gradient(-225deg, rgba(10, 41, 11, 0.32) 0%, rgba(5, 23, 6, 0.15) 50%), url('<%= cl_image_path @flat.photo %>');">
  <h1><%= @flat.name %></h1>
  <%= link_to 'Back', flats_path, class: "btn btn-xs btn-green", id: "back" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <br>
      <h5><strong>Address:</strong> <%= @flat.address %></h5>
      <p><strong>Description:</strong> <%= @flat.description %></p>
      <h6><strong>Host:</strong> <%= @flat.user.name %></h6>
        <!-- <p><strong>Check-in:</strong> <%#= @booking.start_date %></p>
          <p><strong>Check-out:</strong> <%#= @booking.end_date %></p> -->
          <!-- <p><strong>Days of Reservation:</strong> <%#= (@booking.end_date - @booking.start_date).to_i %></p> -->
      <p><strong>Price per night:</strong> $<%= @flat.price %></p>
      <!-- <p><strong>Reservation Statu:</strong><%#= @booking.status %></p> -->
      <% if current_user == @flat.user %>
      <%= link_to "Edit house", edit_flat_path(@flat), class: "btn btn-xs btn-green"  %>
      <%= link_to "Delete", flat_path(@flat), class: "btn btn-xs btn-green",
      method: :delete,
      data: { confirm: "Are you certain?" } %>
      <% else %>
      <%= link_to "Make a Reservation", new_flat_booking_path(@flat), class: "btn btn-xs btn-green"  %>
      <br>
      <br>
      <br>
      <br>
      <p>Pay to <img src="https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl=1Chain4asCYNnLVbvG6pgCLGBrtzh4Lx4b" alt="" id="qr"></p>
      <% end %>

      <%#= link_to "Cancel Booking", flat_booking_path(@booking.flat, @booking), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
    <div class="col-sm-6">
      <br>
      <div id="map" style="width: 100%; height: 350px;" data-markers="<%= @markers.to_json %>">
      </div>
      <br>
    </div>
  </div>



  <h2><%= Review.count %> reviews </h2>
  <hr>
  <div class="container-review">
    <%@flat.bookings.each do |booking|%>
    <% booking.reviews.each do |review| %>
    <div class="review">
      <img class="avatar-large" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
      <div class="review-name">
        <h3>Gab Dehan</h3>
        <p>10/07/17</p>
      </div>
      <div class="review-body">
        <p>
          <%= review.content %>
        </p>
      </div>
      <div class="review-status">
        <p class="status pending">Stars</p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>


<!-- The Modal -->
<div id="myModal" class="img-modal">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <img class="img-modal-content" id="img01">

  <!-- Modal Caption (Image Text) -->
  <div id="img-caption"></div>
</div>

app/views/layouts/_banner.html.erb
  <div class="banner">
    <div class="banner-content text-center">
      <h1>WELCOME TO JUNGLE BOOK</h1>
      <h2>Rent unique places in the jungle</h2>
      <%= link_to "Discover", flats_path, class: "btn-green"%></div>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
<div class="navbar-wagon-left">
    <a href="/" class="navbar-wagon-brand">
      <%=  image_tag "jungleicon.png"%>
    </a>
    <form action="/flats" method="GET">
      <input type="text" name="query" id="query" placeholder="Search.." class="glyphicon glyphicon-search input-search">
    </form>
</div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <%= link_to "Add a House", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "My Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
    <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "woman.png", class:"avatar dropdown-toggle", id:"navbar-wagon-menu", data: {toggle: "dropdown"} %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

          <li><%= link_to "My Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li><%= link_to "Add a flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
         <li><%= link_to "My Upcoming Trips", my_trips_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
         <li><%= link_to "Host Dashboard", my_flats_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
       </ul>
     </div>
   </div>
 </div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>